using System;
using System.Collections.Generic;
using System.Text;

namespace TRGameCheck.Command.Scene
{
    public enum CommandId
    {
        CMD_ACTION_END = 0,//0:事件结束
        CMD_CHILD_ACTION,//1:子事件设定
        CMD_CHILD_INFO_ACTION,//2:子事件设定带信息
        CMD_ELSE,//3:else
        CMD_REQUEST_TEST,//4:询问测试
        CMD_TEST_VALUE, //5:变量测试
        CMD_FORCE_LIMIT,//6:出场限制
        CMD_TEST_START_BATTLE,//7:出战测试
        CMD_MENU_VISIBLE,//8:菜单处理
        CMD_DELAY_SET,//9:延时
        CMD_INIT_VALUE,//a:初始化局部变量
        CMD_SET_VALUE,//b:变量赋值
        //	CMD_c,//c:结束Section
        //	CMD_BATTLE_END,//d:结束Scene
        CMD_ADD_TASK,//c:添加任务
        CMD_DEL_TASK,//d:删除任务
        CMD_TEST_TASK,//e:测试任务步骤
        CMD_SET_TASK_STEP,//f:设置任务步骤
        CMD_CHANGE_TASK_DESC,//10:修改任务描述
        CMD_SCENE_CHANGE,//11:剧本跳转
        CMD_SHOW_CHOICE,//12:选择框
        CMD_CASE,//13:case
        CMD_ACTOR_TALK,//14:对话
        CMD_ACTOR_TALK2,//15:对话2
        CMD_NORMAL_INFO,//16:信息
        CMD_SCENE_NAME,//17:场所名
        CMD_EVENT_NAME,//18:事件名称设定
        CMD_VICTORY_CONDITION,//19:胜利条件
        CMD_SHOW_VICTORY_CONDITION,//1a:显示胜利条件
        CMD_LEAVE_MSG_SHOW_OR_NOT,//1b:撤退信息是否显示设定
        CMD_DRAW,//1c:绘图
        CMD_1d,//1d:调色板设定
        CMD_1e,//1e:武将重绘
        CMD_CHANGE_VIEWPOINT,//1f:地图视点切换
        CMD_HEAD_STATE_SET,//20:武将头像状态设置
        CMD_ADD_MAP_ELEM,//21:战场物体添加
        CMD_MOVIE_SET,//22:动画
        CMD_SOUND_SET,//23:音效
        CMD_MUSIC_SET,//24:CD音轨
        CMD_TEST_ACTOR_POS,//25:武将进入地点测试
        CMD_TEST_ACTOR_AREA,//26:武将进入指定区域测试
        CMD_BG_SET,//27:背景显示
        CMD_28,//28:?三国地图显示？
        CMD_MAP_FACE_APPEAR,//29:地图头像显示
        CMD_MAP_FACE_MOVE,//2a:地图头像移动
        CMD_MAP_FACE_DISAPPEAR,//2b:地图头像消失
        CMD_MAP_TELL_INFO,//2c:地图文字显示
        CMD_TEST_ACTOR_CLICKED,//2d:武将点击测试
        CMD_TEST_ACTOR_BORDER,//2e:武将相邻测试
        CMD_CLEAR_ACTOR,//2f:清除人物
        CMD_ACTOR_APPEAR,//30:武将出现
        CMD_ACTOR_DISAPPEAR,//31:武将消失
        CMD_ACTOR_MOVE,//32:武将移动
        CMD_ACTOR_TURN,//33:武将转向
        CMD_ACTOR_ACTION,//34:武将动作
        CMD_ACTOR_CHANGE_IMAGE,//35:武将形象改变
        CMD_TEST_ACTOR_STATE,//36:武将状态测试
        CMD_MONEY_SCENE_ROUTE_TEST,//37:钱、剧本跳转、忠奸测试
        CMD_SET_ACTOR_ABILITY,//38:武将能力设定
        CMD_ACTOR_LEVEL_UP,//39:武将等级提升
        CMD_MONEY_CHANGE,//3a:钱、剧本跳转、忠奸设置
        CMD_ARMY_CHANGE,//3b:武将加入和离开
        CMD_TEST_ARMY_COME,//3c:武将加入测试
        CMD_GET_GOOD,//3d:获得物品
        CMD_GOOD_SET,//3e:加入装备设定
        CMD_TEST_ROUND,//3f:回合测试
        CMD_TEST_ACTION_SIDE,//40:行动方测试
        CMD_TEST_ACTOR_NUM,//41:战斗人数测试
        CMD_TEST_VICTORY,//42:战斗胜利测试
        CMD_TEST_FAIL,//43:战斗失败测试
        CMD_BATTLE_INIT,//44:战斗初始化
        CMD_BATTLE_SET_VALUE,//45:战场全局变量
        CMD_DISPATCH_FRIEND,//46:友军出场设定
        CMD_DISPATCH_ENEMY,//47:敌军出场设定
        CMD_SET_BATTLE_GOOD,//48:敌军装备设定
        CMD_49,//49:战斗结束
        CMD_CONFIG_OWN_FORCE,//4a:我军出场强制设定
        CMD_DISPATCH_OWN,//4b:我军出场设定
        CMD_SET_ACTOR_VISIBLE,//4c:隐藏武将出现
        CMD_CHANGE_ACTOR_STATE,//4d:武将状态变更
        CMD_CHANGE_ACTOR_AI,//4e:武将方针变更
        CMD_BATTLE_ACTOR_TURN,//4f:战场转向设置
        CMD_BATTLE_ACTOR_ACTION,//50:战场动作设置
        CMD_BATTLE_FIGHT_END,//51:战场恢复行动权
        CMD_CHANGE_ACTOR_OCCU,//52:兵种改变
        CMD_BATTLE_ACTOR_LEAVE,//53:战场撤退
        CMD_BATTLE_LEAVE_COMFORM,//54:战场撤退确认
        CMD_BATTLE_ACTOR_RELIVE,//55:战场复活
        CMD_SET_AIR_TYPE,//56:天气类别设定
        CMD_SET_CUR_AIR,//57:当前天气设定
        CMD_SET_BATTLE_BARRIER,//58:战场障碍设定
        CMD_SET_BATTLE_BONUS,//59:战利品设定
        CMD_BATTLE_START,//5a:战场操作开始
        CMD_BATTLE_HIGHLIGHT_AREA,//5b:战场高亮区域
        CMD_BATTLE_HIGHLIGHT_ACTOR,//5c:战场高亮人物
        CMD_SET_MAX_ROUND,//5d:回合上限设定
        CMD_TEST_ACTOR_NOT_SAME,//5e:武将不同测试
        CMD_PK_END,//5f:单挑结束
        CMD_PK_ACTOR_APPEAR,//60:单挑武将出场
        CMD_PK_SHOW_K_O,//61:单挑胜负显示
        CMD_PK_ACTOR_DIE,//62:单挑阵亡
        CMD_PK_ACTOR_TALK,//63:单挑对话
        CMD_PK_ACTION,//64:单挑动作
        CMD_PK_ATTACK1,//65:单挑攻击1
        CMD_PK_ATTACK2,//66:单挑攻击2
        CMD_CHAPTER_NAME,//67:章名
        CMD_PK_START,//68:单挑开始
        CMD_69,//69:旁白
        CMD_6a,//6a:
        CMD_CALL_MAGIC,//6b:法术召唤
        CMD_MAX
    };
}
